// <auto-generated />
using System;
using BillPayment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillPayment.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20201119025644_paymentservice")]
    partial class paymentservice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BillPayment.Models.BillServices", b =>
                {
                    b.Property<int>("BillNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BillAmt")
                        .HasColumnType("float");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillNo");

                    b.ToTable("BillServices");
                });

            modelBuilder.Entity("BillPayment.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int?>("BillNo")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillNo");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BillPayment.Models.Payment", b =>
                {
                    b.HasOne("BillPayment.Models.BillServices", "Bills")
                        .WithMany()
                        .HasForeignKey("BillNo");

                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
